package fsegs.pfebackendemnagouuiaa.entities;

public enum Role {
    ADMINISTRATEUR,
    ENCADRANT_PROFESSIONNEL,
    ENCADRANT_ACADEMIQUE,
    AGENT_STAGE,
    RESPONSABLE_SERVICE_STAGES,
    RESPONSABLE_UNIVERSITAIRE_STAGES,
    RESPONSABLE_ENTREPRISE,
    STAGIAIRE
}
